name: 'wc_2026'
version: '1.0.0'
profile: 'wc_2026'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  wc_2026:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: mart